### PR TITLE
Add matrix outer product

### PR DESCRIPTION
**Pull request by tcolgate**
AM I being naive, or is this a reasonable implementation of outer product for matrices? I've tested against 

http://tryapl.org/?a=%283%202%20%u2374%20%u23736%29%20%20%u2218.+%203%203%20%u2374%u23739&run

vs

`( 3 2 rho iota 6) o.+ 3 3 rho iota 9`

Both shape and values seem fine

I'd like to edge ivy toward being able to implement the game of life one liner. This was the first hurdle.

### CODE REVIEW

**Comment by robpike** [comment]
All edits go into dev branch, not master.

The change looks good otherwise. Thanks.

The one-liner is a great goal. In my nearly nonexistent spare time I'm trying to make ops be first-class, which will make some things easier to do, including the one-liner. Long way to go yet though.

**Comment by tcolgate** [comment]
I've updated the pull base, and rebased on dev.
I've had a rough hack and removing the restrictions on matricies, to permit scalar matricies, it probably breaks lots of things. I added an `enclose` op,  and doing `(-1 0 1) o.rot enc 4 4 rho iota 16`, display breaks horribly, but the actual data looks OK. Doing things properly will require some proper design, so I'll get some more experience with other things first.

**Comment by robpike** [comment]
Please delete the leading space inside the parens of the example

**Comment by tcolgate** [comment]
Can't squash the commit from the web interface. I'll have to leave it until Wednesday.

**Comment by tcolgate** [comment]
@robpike squashed and pushed. (FYI, I should already have signed the CLA, tcolgate at gmail dot com)

**Comment by robpike** [comment]
Thanks!

**Comment by robpike** [comment]
Sigh, I should have cherry-picked before merge. It doesn't build in the dev branch at tip:

value/eval.go:200: undefined: Binary
value/eval.go:200: undefined: opName


Can you please investigate and fix?

**Comment by shurcooL** [comment]
> investigate

Based on the code in the similar case for `Vector` above, the fix is:

```diff
-m.data[index] = Binary(c, vu, opName, vv)
+m.data[index] = c.EvalBinary(vu, op, vv)
```

This is needed after the clean up refactor in commit eaf0cfd208d900e6b659c7032a6b76266631a833, which [changed the Vector case in that way](https://github.com/robpike/ivy/commit/eaf0cfd208d900e6b659c7032a6b76266631a833#diff-45736597303cd689ac33ab0b6925f475R186).

**Pull request merged**
