### PR TITLE
ivy: in binary iota return highest index of left argument when not found

### PR DESCRIPTION
**Pull request by pstuifzand**
When origin is set to 0, currently iota will return 0 for missing items
and the first items. When origin is set to 1, iota will also return for
missing items, but these can't be used as an index.
This change makes it so itota returns the max index of the left
argument. This value can be used to index in an array.

     1 -1 0["()" iota "(1 + (4 * 5))"]
         1 0 0 0 0 1 0 0 0 0 0 -1 -1

### CODE REVIEW

**Comment by robpike** [comment]
There is a bug, but this isn't the fix for that particular bug. The problem is that binary iota doesn't subtract the origin from the response; it always returns zero. Easy to fix. But....

Your CL changes the behavior to contradict the documentation, although it doesn't update the documentation, which points out that ivy differs from APL here. Maybe it shouldn't. Perhaps the behavior you want (and APL shares) is the way to go, as it avoids -1 indexes. But if so, the docs have to be updated as well as the tests.

**Comment by rsc** [comment]
I don't believe we should change something this fundamental at this point. 
0 is just as good as the max index, and arguably better.
It should just be -1+origin instead of a hard-coded 0.

**Comment by rsc** [comment]
I have a pending PR fully implementing multidimensional binary iota.
I've added a commit in that stack to fix the failure result to match the docs (origin-1).

**Comment by pstuifzand** [comment]
@rsc Thank you for fixing the bug and showing how useful ivy is in the AoC videos :)

**Pull request closed without merging**
